volumes:
  pgdata:

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_todo_list
      - DB_PORT=5432
      - SERVER_PORT=9000
    ports:
      - "9000:9000"
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /usr/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    hostname: db
    command: postgres
    user: postgres
    environment:
      - POSTGRES_DB=go_todo_list
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    name: go_todo_list
