// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        int64
	Name      pgtype.Text
	Complete  pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
